name: Test SPDX Checker Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run SPDX Checker
        uses: ./
        with:
          target-license: 'MIT'
          file-paths: 'tests/test_file.py'
          continue-on-error: false
          fix: false
          extensions: 'py'
          exclude: '**/__init__.py'